---
resources:
- name: github-resource
  type: git
  source:
    uri: https://github.com/cicd-concourse-ci.git

jobs:
- name: python-hello-world
  public: true
  plan:
  - get: github-resource
  - task: hello-world
    file: github-resource/task_hello_world.yml
