---
resources:
- name: github-code
  type: git
  source:
    uri: https://github.com/whewawal/cicd-concourse-ci.git
    branch: master

jobs:
- name: unit-test
  public: true
  plan:
  - get: github-code
  - task: run-unit-test
    file: github-code/unit-test.yml 

